name: Release Jfrog Kubelet Plugin
# # This workflow releases the Jfrog Kubelet Plugin
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
jobs:
  release:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import GPG Private Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 -d | gpg --batch --yes --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
